title: Kaj Printz Madsen
description: Web & Backend Engineer
site_title: '@kpm - Kaj Printz Madsen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: guanox
email: kajprintz@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 