title: Kaj Printz Madsen
description: Web & Backend Engineer
site_title: '@kpm - Kaj Printz Madsen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: nc-kpm
linkedin_username: kaj-printz-madsen-b297b5167
email: kajprintz@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

cv: assets/pdf/CV.pdf

# Google Analytics ID
google_analytics: 